export class SizeConstant {
  static readonly MID_RADIUS = 10;
}

export class StyleConstants {
  /**
   * Component width percentage: 100%.
   */
  static readonly FULL_WIDTH: string = '100%';

  static readonly TITLE_BLUR: BlurStyle = BlurStyle.BACKGROUND_ULTRA_THICK;
  /**
   * Component height percentage: 100%.
   */
  static readonly FULL_HEIGHT: string = '100%';

  static readonly BOLD_FONT_WEIGHT = 700;
  /**
   * Translate value of the collection text.
   */
  static readonly TRANSLATE_X: number = 10;

  /**
   * Translate value of the number of playbacks.
   */
  static readonly TRANSLATE_Y: string = '-100%';

  /**
   * Translate value of the player area on the bottom.
   */
  static readonly TRANSLATE_PLAYER_Y: string = '-48vp';

  static readonly NORMAL_RADIUS: number = 10;

  static readonly SONG_TITLE_FONT_SIZE = 20;

  static readonly SONG_SINGER_FONT_SIZE = 14;
}